### ISSUE TITLE
Few more sites to add

### ISSUE THREAD

**Issue by scriptzteam** [metastck/putler-doser#6]
If you have time you can compare sites in this nice uptime checker :D There are few you probably miss?

https://pieceofshit.pw/status

**Comment by metastck** [comment]
added

**Comment by scriptzteam** [comment]
Thanks :)
Is it possible to keep the urls with ending trailing slash like the other?

**Comment by piotrek94692** [comment]
> Thanks :) Is it possible to keep the urls with ending trailing slash like the other?

Fixed in #9
